name: Build and Deploy to Kubernetes

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Kubernetes 配置文件
        run: |
          kubectl get deployments
