name: Docker Image CI/CD

on:
  push:
    branches:
      - "*"
    # paths:
    #   - "server/service/gateway/**"
    #   - "server/service/other/**"
    #   - "server/common/**"
    #   - "server/utils/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image for service user
        # if: contains(github.event.pushed_paths, 'server/service/b/**')
        run: |
          service_name='user'
          image_name=qiji-${service_name}-test
          ./version_upgrade.sh ${{ steps.branch_name.outputs.branch }} $image_name
          # # new_version=$(version_upgrade.sh ${{ steps.branch_name.outputs.branch }} $image_name)

          # echo "Service ${service_name} image tag: $new_version"

      - name: Build and push Docker image for service github-actions-test
        # if: contains(github.event.pushed_paths, 'server/service/gateway/**')

        run: |
          service_name='github-actions-test'
          image_name=github-actions-test
          # new_version=$(version_upgrade.sh ${{ steps.branch_name.outputs.branch }} $image_name)

          # echo "Service ${service_name} image tag: $new_version"
