name: Docker Image CI/CD

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/docker-build.yml"
      - "server/service/user/**"
      - "server/service/actions/**"
      - "server/common/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get branch name
        id: branch_name
        run: |
          echo "CURRENT_PUSHED_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed_files
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD | tr '\n' ',')
          echo "changed_files $changed_files"
          echo "CHANGED_FILES=${changed_files}" >> $GITHUB_OUTPUT

      - name: Print changed files
        run: |
          echo "branch ${{ env.CURRENT_PUSHED_BRANCH_NAME }}"
          echo "changed_files ${{ env.CHANGED_FILES }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image for service user
        # 只当目标service的代码或者common、utils下的代码变更才会执行该步骤
        if: "contains(env.CHANGED_FILES, 'server/service/user/') || contains(env.CHANGED_FILES, 'server/service/utils/') || contains(env.CHANGED_FILES, 'server/service/common/') || contains(env.CHANGED_FILES, '.github/workflows/docker-build.yml')"
        run: |
          service_name='user'
          image_name=qiji-$service_name-cicd-test
          dockerfile_path=server/service/$service_name/Dockerfile
          new_version=$(./version_upgrade.sh ${{ steps.branch_name.outputs.branch }} $image_name)


          echo "CURRENT_PUSHED_BRANCH_NAME ${{ env.CURRENT_PUSHED_BRANCH_NAME }}"

          echo "build $service_name service"
          echo "image name is $image_name"
          echo "dockerfile_path is $dockerfile_path"

          echo "Service ${service_name} image tag: $new_version"

      - name: Build and push Docker image for service github-actions-test
        # 只当目标service的代码或者common、utils下的代码变更才会执行该步骤
        if: "contains(env.CHANGED_FILES, 'server/service/actions/') || contains(env.CHANGED_FILES, 'server/service/utils/') || contains(env.CHANGED_FILES, 'server/service/common/') || contains(env.CHANGED_FILES, '.github/workflows/docker-build.yml')"
        run: |
          service_name='actions'
          image_name=qiji-$service_name-cicd-test
          dockerfile_path=server/service/$service_name/Dockerfile
          new_version=$(./version_upgrade.sh ${{ steps.branch_name.outputs.branch }} $image_name)

          echo "build $service_name service"
          echo "image name is $image_name"
          echo "dockerfile_path is $dockerfile_path"

          echo "Service ${service_name} image tag: $new_version"
